apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: poc-custom-hpa
  namespace: testing-monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-metrics
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metricName: request_number_per_second
        targetAverageValue: 100m
